### ISSUE TITLE
앞으로 수정해야할 부분 !

### ISSUE THREAD

**Issue by Lee-s-an** [OpenSource-Team-15-No-Back/Dino-T-Rex#14]
1. 지금 show me now를 누르면 정보가 출력되기는 하는데 
정보의 글씨가 너무 크고, 나는 개인적으로 game over 메세지랑 retry,meun 버튼이 없어지면서 어떤 메모장 같은 이미지에 영화: — , 감독 : — 이렇게 됐으면 좋겠어 !
2. 지금 나머지 dinner이랑, nusic은 똑같은 로직으로 출력하면 됩니다 ! 그냥 그거는 이름만 바꿔서 수정하면될꺼같아 ! 
3. 지금 cactus가 너무위로 올라와 있어서 ㅋㅋㅋㅋ 넘어지지가않음 이거는 찬찬히 고치면 되고~?
4. 게임 시작 직후 장애물과 닿아서 게임이 끝나도 지속적으로 cactus나오는 버그(이후 retry하고 나서는 나오지 정상적으로 작동!)
-1,2,3,4번 해결되면  이슈 close 해주세요~!

**Comment by dlacked** [comment]
우선 현재 2번에서 music 로직과 API는 해결 완료했습니다! 미서도 3번 문제 해결했으니,
1번
2번 (진행 중)
3번 (완료)
4번
현 상태입니다!

**Comment by dlacked** [comment]
+5. Retry 이후 점수가 정상적으로 증가되지 않는 버그

**Comment by dlacked** [comment]
1번 (진행 중)
2번 ✅
3번 ✅
4번

현 상황입니당
