### ISSUE TITLE
개발 버그 및 업데이트해야할 사항들 ! (체크해주세요!)

### ISSUE THREAD

**Issue by Lee-s-an** [OpenSource-Team-15-No-Back/Dino-T-Rex#27]
1. 게임창을 고정해야할꺼같음
-> 음,, 일단 여러모로,, 버그가 생겨서(작아졌을때, 점프랑 cactus나오는게 느려지는데 이때는 그럼 좀 점프나 이런거를 다시 조절해줘야지 얘가 그 장애물을 넘어갈 수 있고, 일단 정상적인 게임 창일때도 ! 스코어 오류가 발생하기때문에 ! 원래대로 고정하는게 좋을꺼같습니다~!!!)
2. Show me Now!! 창을  제가 디자인 사진 보내준것처럼 게임 가운대로 출력되게해줬으면 좋겠어요! (메모 그거는 안하는 걸로하고? 지금 처럼 하는데 위치만 좀 조정해주면 좋을꺼같아요!)
3. 나머지 music이랑  dinner 도 위에 수정사항 고쳐지면 배경을 그거에 맞춰서 수정할께요!!

(수정되는 사항들은 리뷰남겨주세요!~!)

**Comment by dlacked** [comment]
[현재 상황]
혹시 수정 완료한 부분 있으면 Edit 눌러서 여기 편집해주세요!

1번 ✅
2번 ✅
