### ISSUE TITLE
Show Me Now 버튼 수정 요망

### ISSUE THREAD

**Issue by dlacked** [OpenSource-Team-15-No-Back/Dino-T-Rex#30]
Show Me Now 버튼은 1회 클릭하면 바로 Retry, Menu 버튼이 뜰 수 있게끔 수정 부탁드립니다.

**Comment by Lee-s-an** [comment]
일단 수정했는데 movie를 표본으로 수정했는데, retry , menu 버튼이 위치 조정에 대한 생각을 좀더 해보고, movie game over 폰트 에러발생

**Comment by dlacked** [comment]
movie 파트는 Show Me Now 버튼 문제 해결 완료. 추후 Dinner와 Music 수정 예정.

**Comment by dlacked** [comment]
전체 파트의 showMeNow 버튼 문제 해결하였습니다. 1d11b3e
